import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import discussionsRouter from "./discussions";
import newsRouter from "./news";
import groupsRouter from "./groups";
import minyansRouter from "./minyans";
import volunteersRouter from "./volunteers";
import charityRouter from "./charity";
import statsRouter from "./stats";
import platformRouter from "./platform";
import causeSupportersRouter from "./cause-supporters";
import featuredCausesRouter from "./featured-causes";
import communityProjectsRouter from "./community-projects";
import askanusRouter from "./askanus";
import socialRouter from "./social";
import adminRouter from "./admin";
import reservationsRouter from "./reservations";
import supportRouter from "./support";
import likesRouter from "./likes";
import mediaRouter from "./media";
import searchRouter from "./search";
import siteCopyRouter from "./site-copy";
import systemErrorsRouter from "./system-errors";
import engagementRouter from "./engagement";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(discussionsRouter);
router.use(newsRouter);
router.use(groupsRouter);
router.use(minyansRouter);
router.use(volunteersRouter);
router.use(charityRouter);
router.use(statsRouter);
router.use(platformRouter);
router.use(causeSupportersRouter);
router.use(featuredCausesRouter);
router.use(communityProjectsRouter);
router.use(askanusRouter);
router.use(socialRouter);
router.use(adminRouter);
router.use(reservationsRouter);
router.use(supportRouter);
router.use(likesRouter);
router.use(mediaRouter);
router.use(searchRouter);
router.use(siteCopyRouter);

export default router;
